import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { AcademicShell } from "@/components/academic-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { errorText, formatScore, getRole, loadGrades, loadStudents } from "@/lib/sina-data";
export const Route = createFileRoute("/_authenticated/aluno")({ head: () => ({ meta: [{ title: "Área do aluno — SINA" }, { name: "description", content: "Consulte suas notas e frequência no SINA." }, { property: "og:title", content: "Área do aluno — SINA" }, { property: "og:description", content: "Notas e frequência acadêmica do aluno." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: StudentArea });
function StudentArea() {
  const queryClient = useQueryClient();
  const role = useQuery({ queryKey: ["my-role"], queryFn: getRole });
  const students = useQuery({ queryKey: ["my-students"], queryFn: loadStudents, enabled: role.data === "student" });
  const student = students.data?.[0];
  const grades = useQuery({ queryKey: ["grades", student?.id], queryFn: () => loadGrades(student?.id ?? ""), enabled: !!student });
  const [enrollment, setEnrollment] = useState(""); const [code, setCode] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function claim(e: FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const { data, error } = await supabase.rpc("claim_student", { _enrollment: enrollment.trim(), _code: code.trim() }); setBusy(false); if (error || !data) { setMessage(error ? errorText(error) : "Matrícula ou código inválido, ou já vinculado."); return; } setMessage("Matrícula vinculada."); await queryClient.invalidateQueries({ queryKey: ["my-students"] }); }
  return <AcademicShell title="Área do aluno" subtitle="Meu acompanhamento acadêmico">
    {role.isPending || students.isPending && role.data === "student" ? <p className="mt-8 text-muted-foreground">Carregando…</p> : role.error || students.error ? <p role="alert" className="mt-8 text-destructive">{errorText(role.error ?? students.error)}</p> : role.data === "teacher" ? <p className="mt-8">Sua conta tem acesso de professor. <Link to="/professor" className="text-primary underline">Abrir área do professor</Link></p> : !student ? <section className="mt-9 max-w-lg border-t border-border pt-6"><h2 className="text-lg font-semibold">Vincular minha matrícula</h2><p className="mt-2 text-sm text-muted-foreground">Peça ao professor seu código de vinculação e informe seus dados abaixo.</p><form onSubmit={claim} className="mt-6 space-y-4"><label className="block text-sm font-medium">Matrícula<Input className="mt-2" required value={enrollment} onChange={e => setEnrollment(e.target.value)} /></label><label className="block text-sm font-medium">Código de vinculação<Input className="mt-2" required value={code} onChange={e => setCode(e.target.value)} /></label><Button disabled={busy} type="submit">Vincular matrícula</Button></form>{message && <p role="status" className="mt-4 text-sm">{message}</p>}</section> : <><div className="mt-9 grid gap-5 border-y border-border py-6 sm:grid-cols-3"><div><p className="text-xs uppercase text-muted-foreground">Aluno</p><p className="mt-2 text-lg font-semibold">{student.full_name}</p><p className="text-xs text-muted-foreground">Mat. {student.enrollment}</p></div><div><p className="text-xs uppercase text-muted-foreground">Turma</p><p className="mt-2 text-lg font-semibold">{student.classroom}</p></div><div><p className="text-xs uppercase text-muted-foreground">Frequência</p><p className="mt-2 text-lg font-semibold">{student.attendance === null ? "Não informada" : `${formatScore(student.attendance)}%`}</p></div></div><section className="mt-9"><h2 className="text-xl font-semibold">Notas por disciplina</h2>{grades.isPending ? <p className="mt-5 text-muted-foreground">Carregando notas…</p> : grades.error ? <p role="alert" className="mt-5 text-destructive">{errorText(grades.error)}</p> : grades.data?.length ? <div className="mt-5 overflow-x-auto border-t border-border"><table className="w-full min-w-[500px] text-left text-sm"><thead className="bg-secondary text-muted-foreground"><tr><th className="p-4">Disciplina</th><th className="p-4">Bimestre</th><th className="p-4">Nota</th><th className="p-4">Faltas</th></tr></thead><tbody>{grades.data.map(g => <tr key={g.id} className="border-b border-border"><td className="p-4 font-medium">{g.subject}</td><td className="p-4">{g.period}º</td><td className="p-4 tabular-nums">{formatScore(g.score)}</td><td className="p-4 tabular-nums">{g.absences}</td></tr>)}</tbody></table></div> : <p className="mt-5 text-sm text-muted-foreground">Ainda não há notas registradas para sua matrícula.</p>}</section></>}
  </AcademicShell>;
}
