/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthContinueRouteImport } from './routes/auth-continue'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAlunoRouteImport } from './routes/_authenticated/aluno'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedProfessorRouteImport } from './routes/_authenticated/professor'
import { Route as AuthenticatedAlunoAgendaRouteImport } from './routes/_authenticated/aluno/agenda'
import { Route as AuthenticatedAlunoAvisosRouteImport } from './routes/_authenticated/aluno/avisos'
import { Route as AuthenticatedAlunoDisciplinasRouteImport } from './routes/_authenticated/aluno/disciplinas'
import { Route as AuthenticatedAlunoFrequenciaRouteImport } from './routes/_authenticated/aluno/frequencia'
import { Route as AuthenticatedAlunoMateriaisRouteImport } from './routes/_authenticated/aluno/materiais'
import { Route as AuthenticatedAlunoNotasRouteImport } from './routes/_authenticated/aluno/notas'
import { Route as AuthenticatedAlunoNotificacoesRouteImport } from './routes/_authenticated/aluno/notificacoes'
import { Route as AuthenticatedAlunoTarefasRouteImport } from './routes/_authenticated/aluno/tarefas'
import { Route as AuthenticatedProfessorAgendaRouteImport } from './routes/_authenticated/professor/agenda'
import { Route as AuthenticatedProfessorAlunosRouteImport } from './routes/_authenticated/professor/alunos'
import { Route as AuthenticatedProfessorAtividadesRouteImport } from './routes/_authenticated/professor/atividades'
import { Route as AuthenticatedProfessorAvaliacoesRouteImport } from './routes/_authenticated/professor/avaliacoes'
import { Route as AuthenticatedProfessorComunicacaoRouteImport } from './routes/_authenticated/professor/comunicacao'
import { Route as AuthenticatedProfessorDisciplinasRouteImport } from './routes/_authenticated/professor/disciplinas'
import { Route as AuthenticatedProfessorFrequenciaRouteImport } from './routes/_authenticated/professor/frequencia'
import { Route as AuthenticatedProfessorMateriaisRouteImport } from './routes/_authenticated/professor/materiais'
import { Route as AuthenticatedProfessorNotasRouteImport } from './routes/_authenticated/professor/notas'
import { Route as AuthenticatedProfessorTurmasRouteImport } from './routes/_authenticated/professor/turmas'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthContinueRoute = AuthContinueRouteImport.update({
  id: '/auth-continue',
  path: '/auth-continue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunoRoute = AuthenticatedAlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessorRoute = AuthenticatedProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunoAgendaRoute =
  AuthenticatedAlunoAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoAvisosRoute =
  AuthenticatedAlunoAvisosRouteImport.update({
    id: '/avisos',
    path: '/avisos',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoDisciplinasRoute =
  AuthenticatedAlunoDisciplinasRouteImport.update({
    id: '/disciplinas',
    path: '/disciplinas',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoFrequenciaRoute =
  AuthenticatedAlunoFrequenciaRouteImport.update({
    id: '/frequencia',
    path: '/frequencia',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoMateriaisRoute =
  AuthenticatedAlunoMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoNotasRoute = AuthenticatedAlunoNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedAlunoRoute,
} as any)
const AuthenticatedAlunoNotificacoesRoute =
  AuthenticatedAlunoNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoTarefasRoute =
  AuthenticatedAlunoTarefasRouteImport.update({
    id: '/tarefas',
    path: '/tarefas',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedProfessorAgendaRoute =
  AuthenticatedProfessorAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorAlunosRoute =
  AuthenticatedProfessorAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorAtividadesRoute =
  AuthenticatedProfessorAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorAvaliacoesRoute =
  AuthenticatedProfessorAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorComunicacaoRoute =
  AuthenticatedProfessorComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorDisciplinasRoute =
  AuthenticatedProfessorDisciplinasRouteImport.update({
    id: '/disciplinas',
    path: '/disciplinas',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorFrequenciaRoute =
  AuthenticatedProfessorFrequenciaRouteImport.update({
    id: '/frequencia',
    path: '/frequencia',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorMateriaisRoute =
  AuthenticatedProfessorMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorNotasRoute =
  AuthenticatedProfessorNotasRouteImport.update({
    id: '/notas',
    path: '/notas',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorTurmasRoute =
  AuthenticatedProfessorTurmasRouteImport.update({
    id: '/turmas',
    path: '/turmas',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/auth': typeof AuthRoute
  '/auth-continue': typeof AuthContinueRoute
  '/convite': typeof ConviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/professor': typeof AuthenticatedProfessorRouteWithChildren
  '/aluno/agenda': typeof AuthenticatedAlunoAgendaRoute
  '/aluno/avisos': typeof AuthenticatedAlunoAvisosRoute
  '/aluno/disciplinas': typeof AuthenticatedAlunoDisciplinasRoute
  '/aluno/frequencia': typeof AuthenticatedAlunoFrequenciaRoute
  '/aluno/materiais': typeof AuthenticatedAlunoMateriaisRoute
  '/aluno/notas': typeof AuthenticatedAlunoNotasRoute
  '/aluno/notificacoes': typeof AuthenticatedAlunoNotificacoesRoute
  '/aluno/tarefas': typeof AuthenticatedAlunoTarefasRoute
  '/professor/agenda': typeof AuthenticatedProfessorAgendaRoute
  '/professor/alunos': typeof AuthenticatedProfessorAlunosRoute
  '/professor/atividades': typeof AuthenticatedProfessorAtividadesRoute
  '/professor/avaliacoes': typeof AuthenticatedProfessorAvaliacoesRoute
  '/professor/comunicacao': typeof AuthenticatedProfessorComunicacaoRoute
  '/professor/disciplinas': typeof AuthenticatedProfessorDisciplinasRoute
  '/professor/frequencia': typeof AuthenticatedProfessorFrequenciaRoute
  '/professor/materiais': typeof AuthenticatedProfessorMateriaisRoute
  '/professor/notas': typeof AuthenticatedProfessorNotasRoute
  '/professor/turmas': typeof AuthenticatedProfessorTurmasRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/auth': typeof AuthRoute
  '/auth-continue': typeof AuthContinueRoute
  '/convite': typeof ConviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/professor': typeof AuthenticatedProfessorRouteWithChildren
  '/aluno/agenda': typeof AuthenticatedAlunoAgendaRoute
  '/aluno/avisos': typeof AuthenticatedAlunoAvisosRoute
  '/aluno/disciplinas': typeof AuthenticatedAlunoDisciplinasRoute
  '/aluno/frequencia': typeof AuthenticatedAlunoFrequenciaRoute
  '/aluno/materiais': typeof AuthenticatedAlunoMateriaisRoute
  '/aluno/notas': typeof AuthenticatedAlunoNotasRoute
  '/aluno/notificacoes': typeof AuthenticatedAlunoNotificacoesRoute
  '/aluno/tarefas': typeof AuthenticatedAlunoTarefasRoute
  '/professor/agenda': typeof AuthenticatedProfessorAgendaRoute
  '/professor/alunos': typeof AuthenticatedProfessorAlunosRoute
  '/professor/atividades': typeof AuthenticatedProfessorAtividadesRoute
  '/professor/avaliacoes': typeof AuthenticatedProfessorAvaliacoesRoute
  '/professor/comunicacao': typeof AuthenticatedProfessorComunicacaoRoute
  '/professor/disciplinas': typeof AuthenticatedProfessorDisciplinasRoute
  '/professor/frequencia': typeof AuthenticatedProfessorFrequenciaRoute
  '/professor/materiais': typeof AuthenticatedProfessorMateriaisRoute
  '/professor/notas': typeof AuthenticatedProfessorNotasRoute
  '/professor/turmas': typeof AuthenticatedProfessorTurmasRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apresentacao': typeof ApresentacaoRoute
  '/auth': typeof AuthRoute
  '/auth-continue': typeof AuthContinueRoute
  '/convite': typeof ConviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/professor': typeof AuthenticatedProfessorRouteWithChildren
  '/_authenticated/aluno/agenda': typeof AuthenticatedAlunoAgendaRoute
  '/_authenticated/aluno/avisos': typeof AuthenticatedAlunoAvisosRoute
  '/_authenticated/aluno/disciplinas': typeof AuthenticatedAlunoDisciplinasRoute
  '/_authenticated/aluno/frequencia': typeof AuthenticatedAlunoFrequenciaRoute
  '/_authenticated/aluno/materiais': typeof AuthenticatedAlunoMateriaisRoute
  '/_authenticated/aluno/notas': typeof AuthenticatedAlunoNotasRoute
  '/_authenticated/aluno/notificacoes': typeof AuthenticatedAlunoNotificacoesRoute
  '/_authenticated/aluno/tarefas': typeof AuthenticatedAlunoTarefasRoute
  '/_authenticated/professor/agenda': typeof AuthenticatedProfessorAgendaRoute
  '/_authenticated/professor/alunos': typeof AuthenticatedProfessorAlunosRoute
  '/_authenticated/professor/atividades': typeof AuthenticatedProfessorAtividadesRoute
  '/_authenticated/professor/avaliacoes': typeof AuthenticatedProfessorAvaliacoesRoute
  '/_authenticated/professor/comunicacao': typeof AuthenticatedProfessorComunicacaoRoute
  '/_authenticated/professor/disciplinas': typeof AuthenticatedProfessorDisciplinasRoute
  '/_authenticated/professor/frequencia': typeof AuthenticatedProfessorFrequenciaRoute
  '/_authenticated/professor/materiais': typeof AuthenticatedProfessorMateriaisRoute
  '/_authenticated/professor/notas': typeof AuthenticatedProfessorNotasRoute
  '/_authenticated/professor/turmas': typeof AuthenticatedProfessorTurmasRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/auth'
    | '/auth-continue'
    | '/convite'
    | '/reset-password'
    | '/admin'
    | '/aluno'
    | '/painel'
    | '/perfil'
    | '/professor'
    | '/aluno/agenda'
    | '/aluno/avisos'
    | '/aluno/disciplinas'
    | '/aluno/frequencia'
    | '/aluno/materiais'
    | '/aluno/notas'
    | '/aluno/notificacoes'
    | '/aluno/tarefas'
    | '/professor/agenda'
    | '/professor/alunos'
    | '/professor/atividades'
    | '/professor/avaliacoes'
    | '/professor/comunicacao'
    | '/professor/disciplinas'
    | '/professor/frequencia'
    | '/professor/materiais'
    | '/professor/notas'
    | '/professor/turmas'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/auth'
    | '/auth-continue'
    | '/convite'
    | '/reset-password'
    | '/admin'
    | '/aluno'
    | '/painel'
    | '/perfil'
    | '/professor'
    | '/aluno/agenda'
    | '/aluno/avisos'
    | '/aluno/disciplinas'
    | '/aluno/frequencia'
    | '/aluno/materiais'
    | '/aluno/notas'
    | '/aluno/notificacoes'
    | '/aluno/tarefas'
    | '/professor/agenda'
    | '/professor/alunos'
    | '/professor/atividades'
    | '/professor/avaliacoes'
    | '/professor/comunicacao'
    | '/professor/disciplinas'
    | '/professor/frequencia'
    | '/professor/materiais'
    | '/professor/notas'
    | '/professor/turmas'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apresentacao'
    | '/auth'
    | '/auth-continue'
    | '/convite'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/aluno'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/professor'
    | '/_authenticated/aluno/agenda'
    | '/_authenticated/aluno/avisos'
    | '/_authenticated/aluno/disciplinas'
    | '/_authenticated/aluno/frequencia'
    | '/_authenticated/aluno/materiais'
    | '/_authenticated/aluno/notas'
    | '/_authenticated/aluno/notificacoes'
    | '/_authenticated/aluno/tarefas'
    | '/_authenticated/professor/agenda'
    | '/_authenticated/professor/alunos'
    | '/_authenticated/professor/atividades'
    | '/_authenticated/professor/avaliacoes'
    | '/_authenticated/professor/comunicacao'
    | '/_authenticated/professor/disciplinas'
    | '/_authenticated/professor/frequencia'
    | '/_authenticated/professor/materiais'
    | '/_authenticated/professor/notas'
    | '/_authenticated/professor/turmas'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApresentacaoRoute: typeof ApresentacaoRoute
  AuthRoute: typeof AuthRoute
  AuthContinueRoute: typeof AuthContinueRoute
  ConviteRoute: typeof ConviteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-continue': {
      id: '/auth-continue'
      path: '/auth-continue'
      fullPath: '/auth-continue'
      preLoaderRoute: typeof AuthContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aluno': {
      id: '/_authenticated/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AuthenticatedAlunoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professor': {
      id: '/_authenticated/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof AuthenticatedProfessorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aluno/agenda': {
      id: '/_authenticated/aluno/agenda'
      path: '/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AuthenticatedAlunoAgendaRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/avisos': {
      id: '/_authenticated/aluno/avisos'
      path: '/avisos'
      fullPath: '/aluno/avisos'
      preLoaderRoute: typeof AuthenticatedAlunoAvisosRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/disciplinas': {
      id: '/_authenticated/aluno/disciplinas'
      path: '/disciplinas'
      fullPath: '/aluno/disciplinas'
      preLoaderRoute: typeof AuthenticatedAlunoDisciplinasRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/frequencia': {
      id: '/_authenticated/aluno/frequencia'
      path: '/frequencia'
      fullPath: '/aluno/frequencia'
      preLoaderRoute: typeof AuthenticatedAlunoFrequenciaRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/materiais': {
      id: '/_authenticated/aluno/materiais'
      path: '/materiais'
      fullPath: '/aluno/materiais'
      preLoaderRoute: typeof AuthenticatedAlunoMateriaisRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/notas': {
      id: '/_authenticated/aluno/notas'
      path: '/notas'
      fullPath: '/aluno/notas'
      preLoaderRoute: typeof AuthenticatedAlunoNotasRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/notificacoes': {
      id: '/_authenticated/aluno/notificacoes'
      path: '/notificacoes'
      fullPath: '/aluno/notificacoes'
      preLoaderRoute: typeof AuthenticatedAlunoNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/tarefas': {
      id: '/_authenticated/aluno/tarefas'
      path: '/tarefas'
      fullPath: '/aluno/tarefas'
      preLoaderRoute: typeof AuthenticatedAlunoTarefasRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/professor/agenda': {
      id: '/_authenticated/professor/agenda'
      path: '/agenda'
      fullPath: '/professor/agenda'
      preLoaderRoute: typeof AuthenticatedProfessorAgendaRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/alunos': {
      id: '/_authenticated/professor/alunos'
      path: '/alunos'
      fullPath: '/professor/alunos'
      preLoaderRoute: typeof AuthenticatedProfessorAlunosRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/atividades': {
      id: '/_authenticated/professor/atividades'
      path: '/atividades'
      fullPath: '/professor/atividades'
      preLoaderRoute: typeof AuthenticatedProfessorAtividadesRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/avaliacoes': {
      id: '/_authenticated/professor/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/professor/avaliacoes'
      preLoaderRoute: typeof AuthenticatedProfessorAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/comunicacao': {
      id: '/_authenticated/professor/comunicacao'
      path: '/comunicacao'
      fullPath: '/professor/comunicacao'
      preLoaderRoute: typeof AuthenticatedProfessorComunicacaoRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/disciplinas': {
      id: '/_authenticated/professor/disciplinas'
      path: '/disciplinas'
      fullPath: '/professor/disciplinas'
      preLoaderRoute: typeof AuthenticatedProfessorDisciplinasRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/frequencia': {
      id: '/_authenticated/professor/frequencia'
      path: '/frequencia'
      fullPath: '/professor/frequencia'
      preLoaderRoute: typeof AuthenticatedProfessorFrequenciaRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/materiais': {
      id: '/_authenticated/professor/materiais'
      path: '/materiais'
      fullPath: '/professor/materiais'
      preLoaderRoute: typeof AuthenticatedProfessorMateriaisRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/notas': {
      id: '/_authenticated/professor/notas'
      path: '/notas'
      fullPath: '/professor/notas'
      preLoaderRoute: typeof AuthenticatedProfessorNotasRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/turmas': {
      id: '/_authenticated/professor/turmas'
      path: '/turmas'
      fullPath: '/professor/turmas'
      preLoaderRoute: typeof AuthenticatedProfessorTurmasRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAlunoRouteChildren {
  AuthenticatedAlunoAgendaRoute: typeof AuthenticatedAlunoAgendaRoute
  AuthenticatedAlunoAvisosRoute: typeof AuthenticatedAlunoAvisosRoute
  AuthenticatedAlunoDisciplinasRoute: typeof AuthenticatedAlunoDisciplinasRoute
  AuthenticatedAlunoFrequenciaRoute: typeof AuthenticatedAlunoFrequenciaRoute
  AuthenticatedAlunoMateriaisRoute: typeof AuthenticatedAlunoMateriaisRoute
  AuthenticatedAlunoNotasRoute: typeof AuthenticatedAlunoNotasRoute
  AuthenticatedAlunoNotificacoesRoute: typeof AuthenticatedAlunoNotificacoesRoute
  AuthenticatedAlunoTarefasRoute: typeof AuthenticatedAlunoTarefasRoute
}

const AuthenticatedAlunoRouteChildren: AuthenticatedAlunoRouteChildren = {
  AuthenticatedAlunoAgendaRoute: AuthenticatedAlunoAgendaRoute,
  AuthenticatedAlunoAvisosRoute: AuthenticatedAlunoAvisosRoute,
  AuthenticatedAlunoDisciplinasRoute: AuthenticatedAlunoDisciplinasRoute,
  AuthenticatedAlunoFrequenciaRoute: AuthenticatedAlunoFrequenciaRoute,
  AuthenticatedAlunoMateriaisRoute: AuthenticatedAlunoMateriaisRoute,
  AuthenticatedAlunoNotasRoute: AuthenticatedAlunoNotasRoute,
  AuthenticatedAlunoNotificacoesRoute: AuthenticatedAlunoNotificacoesRoute,
  AuthenticatedAlunoTarefasRoute: AuthenticatedAlunoTarefasRoute,
}

const AuthenticatedAlunoRouteWithChildren =
  AuthenticatedAlunoRoute._addFileChildren(AuthenticatedAlunoRouteChildren)

interface AuthenticatedProfessorRouteChildren {
  AuthenticatedProfessorAgendaRoute: typeof AuthenticatedProfessorAgendaRoute
  AuthenticatedProfessorAlunosRoute: typeof AuthenticatedProfessorAlunosRoute
  AuthenticatedProfessorAtividadesRoute: typeof AuthenticatedProfessorAtividadesRoute
  AuthenticatedProfessorAvaliacoesRoute: typeof AuthenticatedProfessorAvaliacoesRoute
  AuthenticatedProfessorComunicacaoRoute: typeof AuthenticatedProfessorComunicacaoRoute
  AuthenticatedProfessorDisciplinasRoute: typeof AuthenticatedProfessorDisciplinasRoute
  AuthenticatedProfessorFrequenciaRoute: typeof AuthenticatedProfessorFrequenciaRoute
  AuthenticatedProfessorMateriaisRoute: typeof AuthenticatedProfessorMateriaisRoute
  AuthenticatedProfessorNotasRoute: typeof AuthenticatedProfessorNotasRoute
  AuthenticatedProfessorTurmasRoute: typeof AuthenticatedProfessorTurmasRoute
}

const AuthenticatedProfessorRouteChildren: AuthenticatedProfessorRouteChildren =
  {
    AuthenticatedProfessorAgendaRoute: AuthenticatedProfessorAgendaRoute,
    AuthenticatedProfessorAlunosRoute: AuthenticatedProfessorAlunosRoute,
    AuthenticatedProfessorAtividadesRoute:
      AuthenticatedProfessorAtividadesRoute,
    AuthenticatedProfessorAvaliacoesRoute:
      AuthenticatedProfessorAvaliacoesRoute,
    AuthenticatedProfessorComunicacaoRoute:
      AuthenticatedProfessorComunicacaoRoute,
    AuthenticatedProfessorDisciplinasRoute:
      AuthenticatedProfessorDisciplinasRoute,
    AuthenticatedProfessorFrequenciaRoute:
      AuthenticatedProfessorFrequenciaRoute,
    AuthenticatedProfessorMateriaisRoute: AuthenticatedProfessorMateriaisRoute,
    AuthenticatedProfessorNotasRoute: AuthenticatedProfessorNotasRoute,
    AuthenticatedProfessorTurmasRoute: AuthenticatedProfessorTurmasRoute,
  }

const AuthenticatedProfessorRouteWithChildren =
  AuthenticatedProfessorRoute._addFileChildren(
    AuthenticatedProfessorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlunoRoute: typeof AuthenticatedAlunoRouteWithChildren
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProfessorRoute: typeof AuthenticatedProfessorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlunoRoute: AuthenticatedAlunoRouteWithChildren,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProfessorRoute: AuthenticatedProfessorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApresentacaoRoute: ApresentacaoRoute,
  AuthRoute: AuthRoute,
  AuthContinueRoute: AuthContinueRoute,
  ConviteRoute: ConviteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
