-- Legacy migration kept for migration-history compatibility.
-- Initial administrator assignment is intentionally handled outside migrations.
-- This file is a no-op so a fresh environment is not tied to a personal e-mail account.
