CREATE TYPE public.app_role AS ENUM ('student', 'teacher');
CREATE TABLE public.profiles (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, display_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own profile read" ON public.profiles FOR SELECT TO authenticated USING (user_id = (select auth.uid()));
CREATE POLICY "own profile edit" ON public.profiles FOR UPDATE TO authenticated USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
CREATE TABLE public.user_roles (user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role public.app_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id, role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own roles read" ON public.user_roles FOR SELECT TO authenticated USING (user_id = (select auth.uid()));
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
CREATE FUNCTION public.new_account() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ BEGIN INSERT INTO public.profiles (user_id, display_name) VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name','')); INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'student'); RETURN NEW; END $$;
CREATE TRIGGER on_sina_signup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.new_account();
CREATE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE TRIGGER profiles_updated BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TABLE public.students (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), teacher_id uuid NOT NULL REFERENCES auth.users(id), user_id uuid UNIQUE REFERENCES auth.users(id), full_name text NOT NULL CHECK (length(trim(full_name)) > 0), enrollment text NOT NULL, classroom text NOT NULL, attendance numeric(5,2) NOT NULL DEFAULT 100 CHECK (attendance BETWEEN 0 AND 100), claim_code uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (teacher_id, enrollment));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.students TO authenticated; GRANT ALL ON public.students TO service_role;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "teacher students read" ON public.students FOR SELECT TO authenticated USING (teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher'));
CREATE POLICY "student own record read" ON public.students FOR SELECT TO authenticated USING (user_id = (select auth.uid()));
CREATE POLICY "teacher students create" ON public.students FOR INSERT TO authenticated WITH CHECK (teacher_id = (select auth.uid()) AND user_id IS NULL AND public.has_role((select auth.uid()), 'teacher'));
CREATE POLICY "teacher students edit" ON public.students FOR UPDATE TO authenticated USING (teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher')) WITH CHECK (teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher'));
CREATE POLICY "teacher students delete" ON public.students FOR DELETE TO authenticated USING (teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher'));
CREATE TRIGGER students_updated BEFORE UPDATE ON public.students FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TABLE public.grades (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE, subject text NOT NULL CHECK (length(trim(subject)) > 0), period integer NOT NULL CHECK (period BETWEEN 1 AND 4), score numeric(4,2) NOT NULL CHECK (score BETWEEN 0 AND 10), absences integer NOT NULL DEFAULT 0 CHECK (absences >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(student_id, subject, period));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.grades TO authenticated; GRANT ALL ON public.grades TO service_role;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "student grades read" ON public.grades FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.user_id = (select auth.uid())));
CREATE POLICY "teacher grades read" ON public.grades FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher')));
CREATE POLICY "teacher grades create" ON public.grades FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher')));
CREATE POLICY "teacher grades edit" ON public.grades FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher'))) WITH CHECK (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher')));
CREATE POLICY "teacher grades delete" ON public.grades FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.teacher_id = (select auth.uid()) AND public.has_role((select auth.uid()), 'teacher')));
CREATE TRIGGER grades_updated BEFORE UPDATE ON public.grades FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE FUNCTION public.claim_student(_enrollment text, _code uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ BEGIN IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'student') OR public.has_role(auth.uid(), 'teacher') THEN RETURN false; END IF; IF EXISTS (SELECT 1 FROM public.students WHERE user_id = auth.uid()) THEN RETURN false; END IF; UPDATE public.students SET user_id = auth.uid(), claim_code = gen_random_uuid() WHERE enrollment = _enrollment AND claim_code = _code AND user_id IS NULL; RETURN FOUND; END $$;
REVOKE ALL ON FUNCTION public.claim_student(text, uuid) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.claim_student(text, uuid) TO authenticated;